### ISSUE TITLE
Incorrect checksum on downloads.chef.io

### ISSUE THREAD

**Issue by ericmaxwell** [chef-cookbooks/push-jobs#69] opened 2016-03-18 18:40 UTC
**Issue**
On https://downloads.chef.io/push-jobs-client/windows/ the checksum is a SHA1, but the push-job cookbook is expecting a SHA256 checksum (see below attributes) and will fail with the provided SHA1.

node.default['push_jobs']['package_url'] = "http://www.example.com/pkgs/opscode-push-jobs-client-windows-1.1.5-1.windows.msi"
node.default['push_jobs']['package_checksum'] = "a-sha256-checksum"

**Fix**
Download the package to local machine and generate a SHA256 checksum and use the generated SHA256 for the node.default['push_jobs']['package_checksum'] attibute.

**Comment by mmzyk** [comment] 2016-05-24 14:29
This is actually a dupe of #31, so going to close this in favor of that one, since there is a lot more discussion there on the why and how of things. Thanks for this report though, it was nicely done.

**Closed by mmzyk** 2016-05-24 14:29 UTC

**Comment by mmzyk** [comment] 2016-05-24 14:32
Also, while this was a dupe, the issue was also fixed and the SHA256 checksum is now provided.
